name: Basic Commands

on:
 push:
  branches:
   - main
 schedule:
  - cron: "*/2 * * * *" #Every day at midnight UTC
 workflow_dispatch: #Manual trigger

jobs:
 demo-commands:
  runs-on: ubuntu-latest

  steps:
    - name: show current working directory
      run: pwd

    - name: List files in the directory
      run: ls -la
   
  
