name: Basic Commands

on:
 push:
  brancher:
   -main
schedule:
  -cron: *0 0* * *" #Every day at midnight UTC
 workflow_dispatch:#Manual trigger

 job:
  demo-commands:
   runs-on:ubuntu-latest

   steps:
   -name: show current working directory
   run: pwd

   -name: List files in the dirctory
   run: ls-la
   
  
